october edits
QualitativeDataRepository/dpjedi-website pull request #10
Opened 2021-11-02 16:18 UTC by priyasilverstein

resources additions
fixing steering page

2021-11-02 18:16 UTC, adam3smith requested changes
A couple of typos and a couple if questions.

As a more general note, there's a lot of passive voice in this page. I understand why, but at least to me it reads a little weird at times. Might be worth talking about ideas to rephrase in general

2021-11-02 18:16 UTC, adam3smith commented on docs/resources.html
> +				<p>Editors at <a href="https://onlinelibrary.wiley.com/journal/14756811" target="_blank">Personal Relationships</a> have created a “<a href="https://docs.google.com/document/d/1mIzvUz97ThJVwuVZOq
Typo here?

2021-11-02 18:16 UTC, adam3smith commented on docs/resources.html
> +				<p> A set of stable core practices has begun to emerge with regard to data management and sharing. While all are readily available, some require more effort on the part of journals. For example,
Is Iain's affiliation relevant here? I'd be inclined to include it in parentheses

2021-11-02 18:16 UTC, adam3smith commented on docs/resources.html
> +				<p>There may be particular types of data that are more difficult to share -- e.g. data on sensitive topics. For a case study that includes challenges, tools, and future directions of sharing data
Comma after e.g. for consistency?

2021-11-02 18:16 UTC, adam3smith commented on docs/resources.html
> +				<p>In <b>open reviewing</b> everyone knows the identity of everyone. This is argued to increase the accountability of the reviewer, giving less scope for biased or unjustified judgements. <a href
I assume TEXT is a placeholder?

2021-11-03 11:54 UTC, priyasilverstein commented
thanks for catching those! have fixed. will leave passive voice for now, and think about editing in the next round. thanks!

2021-11-09 11:35 UTC, adam3smith requested changes
Sorry, found one more typo. (I usually just fix those, but currently most code review I do is on the phone, and the app doesn't allow that)

2021-11-09 11:38 UTC, priyasilverstein commented on docs/governance.html
> +<li>Rick Gilmore, Databry, Pennsylvania State University</li>
fixed! thanks

2021-11-09 13:30 UTC, merged

2021-11-09 13:30 UTC, adam3smith commented
Thanks!